### ISSUE TITLE
Google Contacts Epic

### ISSUE THREAD

**Issue by barberj** [Cerious/BetterJourney#1]
# As a user I want to be able to import my Google contacts.

## User stories:
- As a user when I go to `http://localhost:3000/google` I will see a button to import google contacts.
- As a user when I click the button to import google contacts I am directed to google to authorize. When authorized google will callback to `http://localhost:3000/google_confirm`
- When the system confirms a google user it will import people leveraging the Google Contacts api. The people will be serialized and shown as JSON to the user.

## Technical Details
- Ruby/Ruby on Rails

**Comment by barberj** [comment]
@Cerious Ask me any questions you may have and go ahead and begin breaking them down into smaller cards so we can measure progress. A card doesn't necessarily have to achieve a story.

**Comment by Cerious** [comment]
- [x] Generate Rails app (Install error, must look at makefile to find the problem w/ 'pg')
- [ ] Allow Rails App to communicate and display views on http://localhost:3000/google (can't connect to posgres server)

- [ ] Add a Header and most importantly a button to the view w/ text 'Import Google Contacts' 

- [ ] Add functionality to the button in the controller

**Comment by Cerious** [comment]
How to add Functionality to Button:

- [ ] Review Oauth article

- [ ] Review Google Api article

- [ ] Review Mvc concepts

- [ ] **Write out code for button**
